name: 'pre-commit'
description: 'This action efficiently runs pre-commit checks. It caches data for pip, pre-commit, and mypy.'

runs:
  using: "composite"
  steps:
  - name: setup
    uses: actions/setup-python@v2

  - name: cache pip
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: ${{ runner.os }}-pip-

  - name: cache pre-commit
    uses: actions/cache@v3
    with:
      path: ~/.cache/pre-commit
      key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: ${{ runner.os }}-pre-commit-

  - name: cache mypy
    uses: actions/cache@v3
    with:
      path:
        ~/.cache/mypy
      key: ${{ runner.os }}-mypy-v1

  - name: run pre-commit
    env:
      MYPY_CACHE_DIR: /home/runner/.cache/mypy  # tell mypy not to use default location for cache so that we can persist it
    shell: bash
    run: |
      set -x
      ls
      mkdir -p ~/.cache/mypy
      pip install pre-commit
      pre-commit run --all-files --show-diff-on-failure
