name: 'pytest'
description: 'This action efficiently runs pytest checks. It caches data for pip.'

inputs:
  runtime_arguments:
    description: "arguments passed on to pytest"
    required: false

runs:
  using: "composite"
  steps:
  - name: setup
    uses: actions/setup-python@v2
    with:
      cache: 'pip' # caching pip dependencies

  - name: install dependencies
    shell: bash
    run: |
      pip install -r requirements.txt
      pip install pytest

  - name: run pytest
    shell: bash
    run: pytest -s --full-trace ${{ inputs.runtime_arguments }}
