name: 'pytest'
description: 'This action efficiently runs pytest checks. It caches data for pip.'

inputs:
  runtime_arguments:
    description: "arguments passed on to pytest"
    required: false

runs:
  using: "composite"
  steps:
  - name: Get python version
    id: python_version
    uses: doo/actions/get-python-version@main

  - name: setup
    uses: actions/setup-python@v4
    with:
      python-version: ${{ steps.python_version.outputs.version }}
    
  - name: Cache virtual environment
    uses: actions/cache@v3
    id: cache-venv
    with:
      path: ./.venv/
      key: ${{ runner.os }}-${{ steps.python_version.outputs.version }}-venv-${{ hashFiles('requirements.txt', 'setup.py') }}-v1

  - name: Make virtual environment with dependencies
    if: steps.cache-venv.outputs.cache-hit != 'true'
    shell: bash
    run: |
      pip install --upgrade pip
      python -m venv ./.venv
      source ./.venv/bin/activate
      pip install -r requirements.txt
      pip install pytest

  - name: run pytest
    shell: bash
    run: |
      source ./.venv/bin/activate
      pytest -s --full-trace ${{ inputs.runtime_arguments }}
