name: 'pytest'
description: 'This action efficiently runs pytest checks. It caches data for pip.'

inputs:
  runtime_arguments:
    description: "arguments passed on to pytest"
    required: false

runs:
  using: "composite"
  steps:
  - name: Get python version
    id: python_version
    shell: bash
    run: echo "::set-output name=version::$(sed -n 's/^PYTHON_VERSION = \([0-9]\.[0-9]\).*/\1/p' Makefile || echo 3.10)"

  - name: setup
    uses: actions/setup-python@v4
    with:
      python-version: ${{ steps.python_version.outputs.version }}
    
  - name: Cache virtual environment
    uses: actions/cache@v3
    id: cache-venv
    with:
      path: ./.venv/
      key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt', 'setup.py', 'Makefile') }}

  - name: Make virtual environment with dependencies
    if: steps.cache-venv.outputs.cache-hit != 'true'
    shell: bash
    run: |
      pip install --upgrade pip
      python -m venv ./.venv
      source ./.venv/bin/activate
      pip install -r requirements.txt
      pip install pytest

  - name: run pytest
    shell: bash
    run: |
      source ./.venv/bin/activate
      pytest -s --full-trace ${{ inputs.runtime_arguments }}
