name: Update config submodule

on:
  workflow_call:
    secrets:
      checkout-token:
        description: 'A token passed used to checkout any submodules, if present'
        required: true

jobs:
  update-config-repo:
    name: Update config repo
    runs-on: ubuntu-latest
    # Only trigger job when PR is triggered by dependabot
    if: ${{ github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'bump config')}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.checkout-token }}
          submodules: recursive

      - name: setup
        uses: actions/setup-python@v2

      - name: update
        run: python3 config/install.py

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'install / update files from config submodule'
          commit_author: 'dependabot[bot] <support@github.com>'
          commit_user_name: 'dependabot[bot]'
          commit_user_email: 'support@github.com'

  label_as_breaking_change:
    name: Label as breaking change
    if: ${{ contains(github.event.pull_request.body, 'breaking change') || contains(github.event.pull_request.body, 'breaking-change') || contains(github.event.pull_request.body, 'breaking_change')}} # not case sensitive
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: breaking-change

  label_as_take_action:
    name: Label as take action
    if: ${{ contains(github.event.pull_request.body, 'take action') || contains(github.event.pull_request.body, 'take-action') || contains(github.event.pull_request.body, 'take_action')}} # not case sensitive
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: take-action
